### ISSUE TITLE
I haven't studied BASIC, but I'd like to challenge translating it into javascript

### ISSUE THREAD

**Issue by greenking19** [coding-horror/basic-computer-games#146]
I haven't studied BASIC, but I'd like to challenge translating it into javascript.
Are there any recommended books? This plan is really great!
I want to be a part of it, too👨🏻‍💻

**Comment by coding-horror** [comment]
I'm not sure, but you are welcome to contribute! Old BASICs are usually quite simple as they ran on computers with 64 *kilobytes* of RAM.

**Comment by greenking19** [comment]
> I'm not sure, but you are welcome to contribute! Old BASICs are usually quite simple as they ran on computers with 64 _kilobytes_ of RAM.

After half a day of study, I have mastered basic writing of BASIC. Code from 48 years ago, nearly half a century ago, can be rewritten in a language that is now available. I'll write it with javascript, and then pull request when I'm done. I'm so excited!!! 
🤩🤩🤩Incredible

**Comment by coding-horror** [comment]
Great! Have at it! Learning is the purpose :)
