### ISSUE TITLE
Should every language be included in the project?

### ISSUE THREAD

**Issue by gcarreno** [coding-horror/basic-computer-games#15]
Hey Jeff(@coding-horror),

Could you please open discussions so we can have an adult conversation about Object Pascal without me coming out as a troll?

I would really appreciate having a non inflamed, factually full type of conversation about it.

At the end, if I can't convince you, I'll gladly close my PRs and we'll never talk about it :smiley: 

Many thanks for your time and please excuse my zeal on the PR comments. I'm a tad old and I have to admit some bias towards my favourite language, Pascal. It's not my intention to come as a troll AND if I did, please accept my **deepest apologies**!!

Cheers,
Gus

**Comment by coding-horror** [comment]
It's OK, I appreciate your enthusiasm.. just bear in mind that if I open the door to Pascal, I have to open the door to pretty much every other language out there, don't I? That makes the project awfully big and complicated. :(

Perhaps we should have a hard-and-fast rule about "must rank on TIOBE" so there's an objective third party involved?

I am by no means anti-Pascal.. I am anti-complexity.. and we have to have limits somewhere otherwise the project gets super complicated, doesn't it?

And I appreciate you reaching out, but I hope you can see where I am stuck here. I really can't have this become an enormous project, including every computer programming language ever.. :(

**Comment by coding-horror** [comment]
In the meantime, bear with me.. this is why I "soft launched" on twitter before I blogged about it, so we can hash out how to approach it.

(It's also why I reduced the scope to the first book rather than both books!)

I was also planning to do a monetary donation to a coding charity (say, Black Girls Code) per program submitted, so if the number of programs submitted increases by 5x, 6x, 7x, 8x, 10x.. that could price me out of donating :(

**Comment by gcarreno** [comment]
Hey Jeff(@coding-horror),

> It's OK, I appreciate your enthusiasm..

Many thanks for this!!

> just bear in mind that if I open the door to Pascal, I have to open the door to pretty much every other language out there, don't I?

Errmm, yeah, didn't thought about it this way. I was a bit involved in making Object Pascal come up.
BUT it makes a ton of sense.

> Perhaps we should have a hard-and-fast rule about "must rank on TIOBE" so there's an objective third party involved?

I'm the worst person to ask for something like this, but I have to admit that these 2 rules make quite a bit of sense.

So if you can come up with the the minimum TIOBE index and name a third person for Object Pascal (I can mention a few) I'll be ever so thankful.

If after you define these rules Object Pascal does not qualify, I'll drop my PRs.

Cheers,
Gus

**Comment by coding-horror** [comment]
I don't think you need to _drop_ the PRs 🤗

They could probably be in a parallel repo?

**Comment by gcarreno** [comment]
Hey Jeff (@coding-horror),

> I don't think you need to drop the PRs :hugs:

I mean drop my insistence on getting them merged.

> They could probably be in a parallel repo?

Tell me more. You've peeked my attention.

Cheers,
Gus

**Comment by jamescurran** [comment]
So, on a similar note, I've just issued a PR where I reference (in the readme) an article (on CodeProject) about a C++ version of Super Star Trek (Console app with identical gameplay, but completely rewritten with fully object-oriented design).

**Comment by gcarreno** [comment]
Hi Jeff(@coding-horror),

> They could probably be in a parallel repo?

Sorry for insisting, but I really am curious about what you mean with this statement.

Could you please elaborate?

Cheers,
Gus

**Comment by coding-horror** [comment]
yes @gcarreno -- what I suggest is linking the implementation from the README.md, as James Curran did for the C++ implementation of Super Star Trek.

**Comment by gcarreno** [comment]
Hi Jeff(@coding-horror),

Yeap, I now see what you mean. Thanks for the better explanation!!

And thanks James(@jamescurran)  for the suggestion!!

Will, submit PRs with modified README.md in a while.

Cheers,
Gus

PS: Should I close this or should you? Or just leave it open as a guide?

**Comment by gcarreno** [comment]
Hey Jeff(@coding-horror)

> I think it's fine to leave open as a guide! 

I agree, thanks!

At the moment I'm creating a kind of mirror project of this one and, like I said, will drill down all 90 something on your list.

Still not sure if I'll mirror all in one go and then "Pascalise" it, or mirror one at a time.

> thanks for your patience and all your contributions so far :hugs:

No problems. And you're quite welcome!

I'll keep you appraised of progress via PRs when I finish each "Pascalisation".

Cheers,
Gus

**Comment by coding-horror** [comment]
Good news! I have an official answer here

https://discourse.codinghorror.com/t/updating-101-basic-computer-games-for-2021/7927/34

These 8 languages are officially included:

1. Java 
2. Python
3.  C#
4. VB.NET
5. JavaScript
6. Ruby
7. Delphi / Object Pascal
8. Perl

So you are clear to pull request in all the Pascal ones @gcarreno ! 🙌

Any other languages, please link them from the README.MD in the root folder for that example @mike239x

**Comment by gcarreno** [comment]
Hey Jeff(@coding-horror),

> So you are clear to pull request in all the Pascal ones @gcarreno ! :raised_hands:

Thank you so very much for this. But are you absolutely sure? I'm still worried about your donation _upgrade_!!

And if you are, then let me ask you something: My plan is to produce 2 versions of each:
1. One in the purest pascal, kinda the same level as possible to the original BASIC
2. One in Object Pascal, with some bells and whistles of OOP

I still consider this only one contribution per BASIC example, so no added burden on your donation!
I'll be dropping each one on it's own folder: `<BASIC folder>/pascal` and `<BASIC folder>/object-pascal`.
Are you OK with this?

Cheers,
Gus

**Comment by coding-horror** [comment]
It is fine, but I will only count one language version of each program toward the donations.. pascal is pascal ;) 

So I suggest a subfolder like

`/pascal`
`/pascal/object`

maybe?

**Comment by gcarreno** [comment]
Hi Jeff(@coding-horror),

> It is fine, but I will only count one language version of each program toward the donations.. pascal is pascal ;)

Yeaps, that's what I meant when I said:

> I still consider this only one contribution per BASIC example, so no added burden on your donation!

so we're in total agreement. And I know it's double the work, but hey, it's my time to invest :smile: 

> So I suggest a subfolder like

I like the idea of only one folder to house both, still not sure on how to structure it after that.
But don't mind me, I'll respect the one folder and then make _my mess_ under there, LOL!
At the moment I'm inclined on:
`pascal/simple`
`pascal/object-pascal`
If I come up with something more clear in terms of context, I'll just use that.

Cheers,
Gus

**Comment by coding-horror** [comment]
I guess that is OK, not a huge fan of language variants because that opens the door to Groovy (Java variant), Raku (Perl variant) etcetera.. we do want to keep it simple.

**Comment by gcarreno** [comment]
Hi Jeff(@coding-horror),

Variants? No, none of that. My goal is to give 2 examples on the same language but with OOP and without OOP.
The OOP version to give an example of more modern practices and the non OOP version as a direct translation from the BASIC example.
It's just double the work for me, not anything else, because it all compiles under the same compiler, the same way.

Cheers,
Gus

**Comment by coding-horror** [comment]
I'll close this out for now as we have an "official" 8 languages, I'd rather keep the scope smaller to start.
