### ISSUE TITLE
Another bug found in tic-tac-toe python port

### ISSUE THREAD

**Issue by olliehcrook** [coding-horror/basic-computer-games#188]
Vertical wins don't work in center or right hand side.
I didn't have time to fix it earlier.

**Comment by danielpiron** [comment]
Thanks a lot for looking into this. This is a work in progress and haven't
had time to devote to it in the past couple of days. Thanks a ton for
scoping this out.

**Comment by danielpiron** [comment]
Gonna get some fixes in tonight.
