### ISSUE TITLE
Multiple versions of a game

### ISSUE THREAD

**Issue by journich** [coding-horror/basic-computer-games#27]
Hi @coding-horror (Jeff),

I wrote Bagels for Java today not realizing you already had a version in the repo.  My bad for not looking first.

Is it worthwhile for me to upload it?  My version is historically very accurate and close to the Basic code i.e. pretty much identical output to the original basic version.  Same with my first submission, I based it on the existing version as much as possible.

Not to say the version submitted isn't good also, of course.

Let me know. 

I am actually pretty keen on writing a version of most of these games in Java, aiming to knock out one game a day (5 a week or so).

Cheers

Tim

**Comment by coding-horror** [comment]
I think it's fine -- we're figuring out how this works as we go! You might consider submitting a PR consolidating styles across the Java ports as we figure out "best practices"?

**Comment by journich** [comment]
Could look at doing that later.  I think right now it's best to just get as many games done as possible.  I won't submit my Bagels version for now.
