### ISSUE TITLE
Game only, or interpreter behaviour as well?

### ISSUE THREAD

**Issue by drewjcooper** [coding-horror/basic-computer-games#294]
You stated that you'd like the game play to the true to the original, and I whole-heartedly agree. But I'm wondering how far you want to take that?

Should we be recreating the BASIC interpreter's input behaviour? The `INPUT` statement takes keyboard input into one or more variables, allowing input as comma-separated values, or single values per line, or a mix.  Should this behaviour, and the built-in BASIC prompts and error messages be duplicated?

**Comment by coding-horror** [comment]
I'm not sure -- what do you think? We want to demonstrate good, modern coding practices most of all.

**Comment by journich** [comment]
My 2c here...

I've maintained the input of the original game in all of the ports I have worked on.  So if it allowed two values to be entered, separated by a comma thats what my port did.  If it allowed 1, I did that. 

In general I've added little to no new functionality or have not changed the way the game worked in any way.

My reasoning not to change input routines is that someone might be looking at the basic code and trying to figure out how to do the same in whatever language they are using.  So probably a good idea to not change the input functionality.

I do make sure I am using modern coding practices throughout though.

**Comment by drewjcooper** [comment]
I agree. I've ported a number of games to C#, and have keep the input behaviour the same as the original, down to the behaviour for incorrect input.

I've thought a couple of times that it might be nice to have a common library for all ports to use to get this common behaviour.

**Comment by journich** [comment]
Thanks @drewjcooper we are on the same page.  I agree it might be a good idea to add a common library for all ports.  Right now I am pretty keen to get all the games ported.
