### ISSUE TITLE
39 Golf includes compiled csharp code

### ISSUE THREAD

**Issue by greg-kennedy** [coding-horror/basic-computer-games#306]
Cloning the repository takes a long time, because entry `39 Golf` contains a "compiled" version of the game for Windows and Linux.  This adds something like 100mb to the repository.

Due to the way Git works I'm not sure it's possible to remove that without force push and mucking up people's forks, but it'd be nice if that could be taken out so `git clone` goes faster.  I leave it to you to sort that out :)

**Comment by coding-horror** [comment]
hmm. I've removed the compiled folder at least..
