### ISSUE TITLE
Removing spaces from the directory names.

### ISSUE THREAD

**Issue by suetanvil** [coding-horror/basic-computer-games#320]
As someone who uses Unix-style command-line tools a **lot**, I find that spaces in file paths tend to make filename completion and basic scripting harder.  This is not a real impediment, just a persistent low-grade annoyance.  That being said, it's trivial to rename the directories to have (e.g.) underscores instead of spaces.  Would you be willing to make the change?

**Comment by suetanvil** [comment]
I've gone ahead and made a pull request at https://github.com/coding-horror/basic-computer-games/pull/321.

**Comment by coding-horror** [comment]
Looks good to me -- if it makes it easier to contribute it is a win!
