### ISSUE TITLE
Misspelled word, Line 177

### ISSUE THREAD

**Issue by doctorgraphics** [coding-horror/basic-computer-games#333]
https://github.com/coding-horror/basic-computer-games/blob/32b77352347f0f6a7c8cb5e2692950df806f8909/01_Acey_Ducey/python/aceyducey.py#L177

The word assessment is misspelled here. The line should read
"final assessment based on how much of the original"

**Comment by coding-horror** [comment]
Can you submit a PR to correct?

**Comment by doctorgraphics** [comment]
Done, I think. I'm kinda new at Github. On a personal note, I've been
reading your blog for years. I am an individual with a disability, with a
degree in information systems. 10 years after graduating, I got a full-time
job programming SQR files almost exactly one year ago. Your blog and some
others like it helped give me the motivation to keep pursuing my dream job.
Thank you. :-)

Kenny R Brown

***@***.***
209-620-9223

**Comment by coding-horror** [comment]
Oh wow thank you so much! I don't see the pull request yet, does this help? You can do it from the web browser:

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by doctorgraphics** [comment]
You're welcome.

**Comment by bugdebugger** [comment]
I think this issue can be closed now as the spelling fix was merged in PR https://github.com/coding-horror/basic-computer-games/pull/335
