### ISSUE TITLE
Bug in King.bas

### ISSUE THREAD

**Issue by pcholt** [coding-horror/basic-computer-games#346]
I think I've found a bug in the incredibly difficult game "King".

Variable `A` is tracking the amount of money the player has, and `V3` seems to be recording the previous turn's tourist income. In any case, on line 170 and 171, we find these two lines

    1450 V3=INT(A+V3)
    1451 A=INT(A+V3)

So... if `V3` begins as zero, the player doubles their money?

I think this is solved by changing the code in line 170

    1450 V3=INT(ABS(V1-V2))

Maybe the original typist made a mistake by repeating the expression from line 171 in line 170?

**Comment by pcholt** [comment]
![image](https://user-images.githubusercontent.com/968129/147877716-8c3c8886-3148-4f19-becd-39827de23159.png)
It's also in my 1979 copy of "Basic Computer Games TRS-80 edition"
![image](https://user-images.githubusercontent.com/968129/147877831-ec22808d-7900-41a3-a39a-69830bc303ee.png)

**Comment by coding-horror** [comment]
fantastic find! Document it in the comments and the readme.md for the game if you would please!

**Comment by pcholt** [comment]
Resolved in latest PR
