### ISSUE TITLE
Java version of Animal does not work

### ISSUE THREAD

**Issue by patimen** [coding-horror/basic-computer-games#369]
It is using the list of questions as a pure list instead of a tree.  So the questions will continue, instead of terminate:
THINK OF AN ANIMAL AND THE COMPUTER WILL TRY TO GUESS IT.
ARE YOU THINKING OF AN ANIMAL ? Y
DOES IT SWIM ? N
IS IT A BIRD ? N
THE ANIMAL YOU WERE THINKING OF WAS A DOG
PLEASE TYPE IN A QUESTION THAT WOULD DISTINGUISH A DOG FROM A BIRD DOES IT FLY
FOR A DOG THE ANSWER WOULD BE N
ARE YOU THINKING OF AN ANIMAL ? Y
DOES IT SWIM ? Y
IS IT A FISH ? N
DOES IT FLY ? 

The "DOES IT FLY" should not appear.

**Comment by coding-horror** [comment]
ah interesting, we should check in with whoever contributed that PR and ask them perhaps?

**Comment by journich** [comment]
I believe @aldrinm is the author of this one.  Can you check out the comments from @patimen and let us know?

Thanks

**Comment by coding-horror** [comment]
We think this has fixed it! Reply if not.
