### ISSUE TITLE
Use top-level statements for C#

### ISSUE THREAD

**Issue by zspitz** [coding-horror/basic-computer-games#380]
For instance, [this](https://github.com/coding-horror/basic-computer-games/blob/main/01_Acey_Ducey/csharp/Program.cs):

```csharp
using System;
using System.Threading;

namespace AceyDucey
{
    /// <summary>
    /// The application's entry point
    /// </summary>
    class Program
    {
        /// <summary>
        /// This function will be called automatically when the application begins
        /// </summary>
        /// <param name="args"></param>
        static void Main(string[] args)
        {
            // Create an instance of our main Game class
            Game game = new Game();

            // Call its GameLoop function. This will play the game endlessly in a loop until the player chooses to quit.
            game.GameLoop();
        }
   }
}
```

could be reduced to this:

```csharp
// Create an instance of our main Game class
Game game = new Game();

// Call its GameLoop function. This will play the game endlessly in a loop until the player chooses to quit.
game.GameLoop();
```

On the other hand, using top-level statements obscures the basic "entry-point" nature of C# and .NET, which may not be a good idea from an educational standpoint.

**Comment by pczajkowski** [comment]
Well, you would also have to add this at the top:
`using AceyDucey;`

And I'm not so sure it would be more readable. But I'm not big fan of top-level statements to be honest.

**Comment by amrojjeh** [comment]
From the docs:
> Top-level statements let you write simple programs for small utilities such as Azure Functions and GitHub Actions. They also make it simpler for new C# programmers to get started learning and writing code.

While the projects here are simple, if my understanding is correct, they're supposed to emulate the conventions of larger projects. So, I would not use top-level statements for this reason.

**Comment by coding-horror** [comment]
Hmm. I would not say we're trying to emulate large projects here. We are emulating SMALL projects, so make choices appropriate for small projects.

**Comment by amrojjeh** [comment]
Got it. If that's the case, then I think it makes sense to use top level statements.

**Comment by journich** [comment]
Thanks @amrojjeh, sounds good!
