### ISSUE TITLE
For C#/VB.NET, keep solution and project file in same directory

### ISSUE THREAD

**Issue by zspitz** [coding-horror/basic-computer-games#381]
Even though Visual Studio by default creates the `.sln` file in the root directory and creates a `.csproj`/`.vbproj` file in a subdirectory with all the project files, I don't think this is really necessary.

For example, [Amazing (C#)](https://github.com/coding-horror/basic-computer-games/tree/main/02_Amazing/csharp) has only four files without a subdirectory; while [Acey Ducey (VB.NET)](https://github.com/coding-horror/basic-computer-games/tree/main/01_Acey_Ducey/vbnet) has the unneeded subfolder.

**Comment by coding-horror** [comment]
@zspitz if you'd like to take this on it would be quite welcome!

**Comment by zspitz** [comment]
OK. I'll work it out, as part of generating a standard template for the C#/VB versions.

**Comment by journich** [comment]
Thanks @zspitz, much appreciated!

**Comment by zspitz** [comment]
I'm rethinking this. When there are multiple projects, then each project should be in the same folder. There are two reasons for multiple projects:

* A separate test project, as in [Train (C#)](https://github.com/coding-horror/basic-computer-games/tree/main/91_Train/csharp) and [War (C#)](https://github.com/coding-horror/basic-computer-games/tree/main/94_War/csharp)
* An abstraction of console output, as in [BombsAway (C#)](https://github.com/coding-horror/basic-computer-games/tree/main/12_Bombs_Away/csharp)

Not sure about the second -- unless we're going to create some shared abstraction of output usable by all the programs, I think having it in each one is just added noise. But I think having test projects is certainly a valid reason.

Moving from a "project-in-same-folder-as-solution" to "project-in-subfolder" requires a bit of work:

1. opening the solution
2. removing the project from within the solution
3. moving the project files into a subfolder  -- `.csproj`/`.vbproj` and all the code files
4. reattaching the `.csproj`/`.vbproj` file from its new location

This is a strong argument for having the project files in a subfolder from the beginning, especially since this is how Visual Studio constructs projects by default.

**Comment by zspitz** [comment]
This is implemented via #520.
