### ISSUE TITLE
Checkers jumps its own pieces, and somehow jumps when it's not in a position to (python)

### ISSUE THREAD

**Issue by hsq-cernansky** [coding-horror/basic-computer-games#395]
It jumps when it's not in position to. Also, it jumps its own pieces on its way to jumping my pieces.

**Comment by coding-horror** [comment]
Hmm. is this a bug in the original, or just the python implementation?

**Comment by hsq-cernansky** [comment]
Playing the same moves in the BASIC version with `vintbas` does not cause the problem, so it looks to be unique to the python version.

**Comment by journich** [comment]
I believe @tsmaster was the person involved with the Python port of Checkers.  Dave, if possible can you take a look at this?

Many thanks

**Comment by tsmaster** [comment]
I'll take a look. Can @hsq-cernansky provide a series of moves that reliably reproduce the problem?

**Comment by tsmaster** [comment]
I played one game vs the AI, and noticed no problems. Will be happy to look further with a repro case. Perhaps also would be good to know what OS and version of Python you're using. I'm testing on Linux with Python 3.9.5.

**Comment by journich** [comment]
Thanks for your help with this @tsmaster.  Lets see what @hsq-cernansky comes back with.

**Comment by hsq-cernansky** [comment]
I will try, and let you know. I can't remember the sequence that got me there but when I get a free moment, I'll attempt to reproduce the issue.
