### ISSUE TITLE
Standardize format of links to external implementations

### ISSUE THREAD

**Issue by eweilnau** [coding-horror/basic-computer-games#397]
### Current Examples

There are currently multiple formats for linking to another implementation in an external repository.

From [/01_Acey_Ducey/README.md](https://github.com/coding-horror/basic-computer-games/blob/main/01_Acey_Ducey/README.md)
```
A Common Lisp port is [here](https://github.com/koalahedron/lisp-computer-games/blob/master/01%20Acey%20Ducey/common-lisp/acey-deucy.lisp).
```

From [/24_Chemist/README.md](https://github.com/coding-horror/basic-computer-games/blob/main/24_Chemist/README.md)
```
[Conversion to C](https://github.com/ericfischer/basic-computer-games/blob/main/24%20Chemist/c/chemist.c)
```

From [/43_Hammurabi/README.md](https://github.com/coding-horror/basic-computer-games/blob/main/43_Hammurabi/README.md)
```
[Port to C language](https://github.com/beyonddream/hamurabi)

[Port to Rust language](https://github.com/beyonddream/hamurabi.rs)
```

From [/84_Super_Star_Trek/README.md](https://github.com/coding-horror/basic-computer-games/blob/main/84_Super_Star_Trek/README.md)
```
#### External Links
 - Super Star Trek in C++ : https://www.codeproject.com/Articles/28399/The-Object-Oriented-Text-Star-Trek-Game-in-C
```

### Template Proposal

I would suggest the following as a template with the list alphabetized by implementation language.
```
#### External Links
 - C: https://github.com/beyonddream/hamurabi
 - Rust: https://github.com/beyonddream/hamurabi.rs
```

**Comment by coding-horror** [comment]
Sure that looks good! I would accept a PR that makes it so!
