### ISSUE TITLE
BASIC compiler for Linux

### ISSUE THREAD

**Issue by qequ** [coding-horror/basic-computer-games#40]
Anyone knows a BASIC compiler working on Linux? I couldn't find any compiler working to run the .bas files

**Comment by gcarreno** [comment]
Hey Alvaro(@qequ),

On the top level [README.md](https://github.com/coding-horror/basic-computer-games/blob/main/README.md) under the header [Project structure](https://github.com/coding-horror/basic-computer-games/#project-structure), Jeff sais:

> Note that Lyle Kopnicky has generously normalized all the code (thanks Lyle!) to run against [Vintage Basic](http://www.vintage-basic.net/download.html) circa 2009

I've downloaded and tested it under Ubuntu 20.10 64b and, as Jeff is a Windows person, it will also run under Windows, I'm guessing.
That link in the `README.md` will get you on the Vintage Basic download page.

Hope that helps :smile: 

Cheers,
Gus

**Comment by aretche** [comment]
Hey @qequ 
I am using www.pc-basic.org in Ubuntu 20.04

**Comment by qequ** [comment]
Oh I didn't read the README carefully :( Thanks for the answer guys!


Cheers!

**Comment by gcarreno** [comment]
Hey Alvaro(@qequ),

> Thanks for the answer guys!

No probs, quite welcome!!

Cheers,
Gus
