### ISSUE TITLE
hamurabi.py does not generate harvest yield properly

### ISSUE THREAD

**Issue by hsq-cernansky** [coding-horror/basic-computer-games#401]
The harvest yield per planted bushel is supposed to be a random integer between 1 and 5.
Instead, the python version always yields 1. This makes the game impossible.

**Comment by coding-horror** [comment]
aha! can we check in with the person who contributed the code?

**Comment by hsq-cernansky** [comment]
Probably a good idea. I am not a great python coder, but I tried to fix it at home. It behaved very oddly and I reverted my changes. Will try again later.

**Comment by coding-horror** [comment]
I merged the above, are we good now?

**Comment by hsq-cernansky** [comment]
Yup, it works a treat!
