### ISSUE TITLE
Kotlin Animal goes into an infinite loop on EOF

### ISSUE THREAD

**Issue by pcholt** [coding-horror/basic-computer-games#418]
Animal.kt goes into an infinite loop, on end-of-file.
`readLine` returns null when end-of-file is reached, so looping back to try `readline` again will not work, it will not prompt again after an end-of-file.
Best to throw an exception on interactive `readLine` sessions returning null:

    return readLine()?.uppercase() ?: throw EndOfInputException()

**Comment by coding-horror** [comment]
can we notify the person who authored that PR?

**Comment by pcholt** [comment]
@patimen Can you have a look at this?

**Comment by patimen** [comment]
Ah, OK. I think I'll switch to `readln()`, which will throw an exception instead of return null. I use it in the other Kotlin code for that reason, I must have missed this one.

https://github.com/coding-horror/basic-computer-games/pull/432

**Comment by journich** [comment]
Thanks @pcholt for the bug report and thanks @patimen for the fix!
