### ISSUE TITLE
Newbie

### ISSUE THREAD

**Issue by salam87v** [coding-horror/basic-computer-games#421]
I'm a newbie playing github, please teach me how?

**Comment by K780420** [comment]
😅

2022년 1월 5일 (수) 오후 4:08, Muhammad Hidayatus Salam ***@***.***>님이
작성:

**Comment by K780420** [comment]
😅😁

2022년 1월 5일 (수) 오후 4:32, 강연 ***@***.***>님이 작성:

**Comment by coding-horror** [comment]
Welcome! Start with https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request
