### ISSUE TITLE
Additional languages?

### ISSUE THREAD

**Issue by vexx32** [coding-horror/basic-computer-games#480]
Is there any desire for additional languages to be added here as well, or are the predefined 8 as far as we want to go here?

Personally I think it'd be useful to include PowerShell as one of the languages here, and potentially even something a bit more adventurous like Rust. Both are pretty well suited to the command-line nature of these games, and I think it'd be very interesting to have those ports around.

**Comment by coding-horror** [comment]
For now we are limiting it to the 8, however, there is some debate around kicking Pascal out if it is not "safe enough" in practice (see another open issue). You are definitely free to create other implementations and link them from the `readme.md` for the game if you like! 🙏

**Comment by Abbabon** [comment]
Sorry to piggy-back over this issue, but it seems relevant :)

If we are aiming at additional memory-safe languages, why not add **Rust** to the list, as a language setting a new standard in memory safety.

**Comment by coding-horror** [comment]
@leha-bot and @Abbabon you are definitely free to create other implementations and link them from the `readme.md` for the game if you like! 🙏

**Comment by stefanhaustein** [comment]
Shameless plug for kotlin: https://github.com/kobjects/konsole/tree/main/shared/src/commonMain/kotlin/org/kobjects/konsole/demo (ok, it's just 4 so far but it's a start O:)

**Comment by Yagi-404** [comment]
And what about Lua ?
It's thread-safe and multi-paradigm 👍

**Comment by mojoaxel** [comment]
I would love to see implementations in [shell script](https://en.wikipedia.org/wiki/Shell_script). Bash is used quite often under a lot of different circumstances and these repository would be an wonderful way to learn the basics!

**Comment by coding-horror** [comment]
@mojoaxel I don't know about shell script, whatever BASH we maintain at Discourse becomes a liability very quickly..

**Comment by mojoaxel** [comment]
@coding-horror I feel you! But it is still wildly used because it is available almost everywhere. I've creates a first example in #635 but I don't mind if nobody is interested in shell scripts ;-)

**Comment by coding-horror** [comment]
Good news! The number of languages is now 10.

C#
Java
JavaScript
Kotlin
Lua
Perl
Python
Ruby
Rust
VB.NET

Rationale here: https://discourse.codinghorror.com/t/updating-101-basic-computer-games-for-2022-and-beyond/7927/116

You can contribute any other languages as you please via the https://github.com/coding-horror/basic-computer-games/tree/main/00_Alternate_Languages folder.
