### ISSUE TITLE
Multiple Java Implementations of 75 Roulette

### ISSUE THREAD

**Issue by LittleTealeaf** [coding-horror/basic-computer-games#488]
Just something I noticed, It seems that two different versions of 75 Roulette were implemented. There's one in a src sub-directory, and another in the base directory. Thoughts? 

My initial thoughts is to separate them into individual folders, but still unsure how to categorize each one

Specifically referring to the #481 and #486 merged pull requests
@andrewmcguinness was the author of the other one.

**Comment by journich** [comment]
@LittleTealeaf and @andrewmcguinness looks like you both worked on the game at the same time!  It happens sometimes that two people decide to work on the game at the same time.

What I would suggest is keeping both of the implementations now as they have been already done, but to put a note in the main folder explaining that two versions exist, and perhaps the differences in approach.

Or just discuss here between the two of you what you think should be in the file, and I'll add the information for you.

Just tag me if you want me to help with this.

**Comment by LittleTealeaf** [comment]
It looks like @andrewmcguinness solution is more object-oriented in nature, and mine would be more iterative? I'm going to make a branch to neaten it up and the make a pull request

**Comment by LittleTealeaf** [comment]
Going to mark this issue as resolved (with the merging of #491 , but still open to changes / modifications if the need arises
