### ISSUE TITLE
Which Python version should I use?

### ISSUE THREAD

**Issue by MartinThoma** [coding-horror/basic-computer-games#661]
[There](https://github.com/coding-horror/basic-computer-games/pull/657) was already a bit of discussion on the Python version to use for this project. I would be happy if we could find a general rule for the whole project.

## Important Facts

**Which Python versions are still officially supported?** [3.7](https://peps.python.org/pep-0537/), [3.8](https://peps.python.org/pep-0569/), 3.9, 3.10. [3.6 no longer receives security updates](https://peps.python.org/pep-0494/) and 3.11 is not stable jet.

**What do people run?** Using [pyenv](https://github.com/pyenv/pyenv) it's pretty easy to switch between Python versions. However, for beginners it might not be so easy. They might use whatever their system has installed. For Ubuntu 20.04, the default Python 3 version is 3.8 ([link](https://packages.ubuntu.com/focal/python3))

My article [Killer Features by Python version](https://python.plainenglish.io/killer-features-by-python-version-c84ca12dba8) lists a few more, but those are the ones I think are interesting for this project:

* 3.7: Dataclasses
* 3.8: f-strings❗❗, TypedDict, 
* 3.9: -
* 3.10: structural pattern matching - we have one project that ([79 slalom](https://github.com/coding-horror/basic-computer-games/blob/main/79_Slalom/python/slalom.py#L82-L99))

## Proposal

My proposal would be the following:

1. Try to keep code runnable on Python 3.8+ to make it easy for people to run.
2. If the original author makes use of a feature like structural pattern matching, the support for older Python versions can be dropped, but it must be clearly stated in the README that this is Python 3.10 only (or similar)
3. PRs which just would adjust existing code and remove support for Python 3.8 / Python 3.9 would be declined, if the new version is not noticably simpler to understand.

Thus CI should support 3.10 so that people are free to use it.

**Comment by coding-horror** [comment]
<img width="627" alt="image" src="https://user-images.githubusercontent.com/1522517/159184225-38045edd-5f0f-4e34-bcdf-b755de50ed18.png">

https://en.wikipedia.org/wiki/History_of_Python#Version_3

I think 3.8 seems like a reasonable choice.. 3.8 was released late 2019.
