### ISSUE TITLE
[python checkers] if a non movable piece is selected it gets stuck

### ISSUE THREAD

**Issue by redital** [coding-horror/basic-computer-games#677]
let me make an example

.    X    .    X    .    X    .    X
.    .    X    .    X    .    X    .
.    X    .    X    .    X    .    X
X    .    .    .    .    .    .    .
.    O    .    .    .    .    .    .
.    .    O    .    O    .    O    .
.    O    .    O    .    O    .    O
O    .    O    .    O    .    O    .

FROM?
0,0
TO?
1,1
TO?
1,0
TO?
0,1
TO?
-1,0
TO?

**Comment by MartinThoma** [comment]
Thank you for reporting this issue! I think I've addressed this bug in the following PR: https://github.com/coding-horror/basic-computer-games/pull/678
