### ISSUE TITLE
Large files in git

### ISSUE THREAD

**Issue by MartinThoma** [coding-horror/basic-computer-games#681]
I've noticed some astonishingly large files in this repository (in the git history):

```
81ebba90f411  1,4MiB buildJvm/build_53_King_kotlin/build/install/build_53_King_kotlin/lib/kotlin-stdlib-1.6.0.jar -- added via fe4219dc5a847f919d35b965789026ffdc3b40b3
eeb85bc8ea11  4,4MiB 53_King/kotlin/king.jar -- added via fe4219dc5a847f919d35b965789026ffdc3b40b3
7c624e47ff0f   25MiB 89_Tic-Tac-Toe/python/TicTacToe_exe/TicTacToe.exe -- added via 3efe6e3ae260800beae7c28ed095960939344581
65c61eb509d6   34MiB 39 Golf/csharp/compiled/linux_x86/golf -- added via 0dbb491ff9b2b22744cb7b5ddf6e6241938b70f0
5222483d2f8c   66MiB 39 Golf/csharp/compiled/windows_x86/golf.exe -- added via 0dbb491ff9b2b22744cb7b5ddf6e6241938b70f0
``` 

They are all already deleted, but still in the git history. This makes this repository way bigger than necessary. I've just seen a warning by Github about which I was confused ... and especially about the executable in `89_Tic-Tac-Toe/python`. I initially thought I had done something wrong.

## Re-write history

We could remove those from the git history: https://stackoverflow.com/a/2158271/562769
However, I have to admit that re-writing git history always feels scary to me

## Prevent it in future

I would like to do two things:

1. Add the pre-commit hook [`check-added-large-files`](https://github.com/pre-commit/pre-commit-hooks#check-added-large-files)
2. Check in the CI if a large file was added (the simplest way to do it would be to run pre-commit in CI, but I would like to avoid that ... I need to check how to do this)

Does this sound like a good idea to you?

What would be a good maximum file size?

**Comment by coding-horror** [comment]
Yes that sounds good. Let’s re write history and prevent files larger than
1mb.

**Comment by MartinThoma** [comment]
## Git History Rewrite

I propose to do the following:

1. Merge all current branches - or ask the people to copy their changes
2. Ask contributors to (1) delete their fork / repository (2) fork again (3) clone again
3. Rewrite the history as follows:

```
# Merge all local / remote branches!

# Delete all local branches
git branch -D $(git branch)

# Create backup:
git bundle create backup.bundle --all

# Remove big files
git filter-branch --prune-empty -d /dev/shm/scratch \
  --index-filter "git rm --cached -f --ignore-unmatch '39 Golf/csharp/compiled/windows_x86/golf.exe'" \
  --tag-name-filter cat -- --all

git filter-branch -f --prune-empty -d /dev/shm/scratch \
  --index-filter "git rm --cached -f --ignore-unmatch '39 Golf/csharp/compiled/linux_x86/golf'" \
  --tag-name-filter cat -- --all

git filter-branch -f --prune-empty -d /dev/shm/scratch \
  --index-filter "git rm --cached -f --ignore-unmatch '89_Tic-Tac-Toe/python/TicTacToe_exe/TicTacToe.exe'" \
  --tag-name-filter cat -- --all

git filter-branch -f --prune-empty -d /dev/shm/scratch \
  --index-filter "git rm --cached -f --ignore-unmatch '53_King/kotlin/king.jar'" \
  --tag-name-filter cat -- --all

git filter-branch -f --prune-empty -d /dev/shm/scratch \
  --index-filter "git rm --cached -f --ignore-unmatch 'buildJvm/build_53_King_kotlin/build/install/build_53_King_kotlin/lib/kotlin-stdlib-1.6.0.jar'" \
  --tag-name-filter cat -- --all
  
# Force-push!!!!
```

**Comment by MartinThoma** [comment]
The effect of this:

```
$ ls -lh
  74M  backup.bundle
 5,4M  repo-after-history-rewrite.bundle
 4,9M  repo-after-history-rewrite-and-clean.bundle
```

**Comment by coding-horror** [comment]
I think we have definitely decided we don't want any build or IDE specific files in the repo, so proceed accordingly there...

**Comment by MartinThoma** [comment]
If I should do it, I would give @AlaaSarhan time until Monday to finish https://github.com/coding-horror/basic-computer-games/pull/404 . If possible, I would like to prevent open PRs.

Should I do it? Does it sound good to wait until #404 is merged / Monday (whatever is earlier)?

**Comment by coding-horror** [comment]
Sure! Sounds good to me.

**Comment by MartinThoma** [comment]
The history re-write is done. **Please clone from the current repository**

**Comment by coding-horror** [comment]
OK! I cloned the repo from scratch and it looks good to me! Thank you!
