### ISSUE TITLE
Approach question

### ISSUE THREAD

**Issue by ptdecker** [coding-horror/basic-computer-games#69]
So, is the idea here to reproduce the original game as published as faithfully as possible with respect to verbiage, spacing, etc., and to keep the code a simple and straight-forward translation?  Or, is it to get all fancy, add features, and cram code full of "better" things such as objects, etc.?

**Comment by ptdecker** [comment]
I re-read the main README and I think it answers my questions and the PR I just submitted complies with the spirit.  I would go ahead and close this issue as such, but looking through some of the other code submissions they appear to use much fancier things.

**Comment by coding-horror** [comment]
Cool -- I'm happy to clarify anything in the readme, I need to make another pass.. there is definite "cleverness" in some of the existing BASIC code, our goal is to make it as educational and simple / straightforward as possible.
