### ISSUE TITLE
Mastermind.py has trouble counting black and white pegs. 

### ISSUE THREAD

**Issue by jnellis** [coding-horror/basic-computer-games#715]
@AnthonyMichaelTDM 
@MartinThoma 

I was working on reverting #611 because it was just wrong and decided to run a few games to test it was doing the right thing. Using Python 3.8.10.  There's also a bit of debug printf's regarding what its doing while taking the computer is guessing. 
 

There's some screwy stuff going on with this port. Here is an example of it not validating ANY possible answer on the simplest  puzzle of two colors and two positions (4 total possible solutions.)  
```
 Mastermind                               
Creative Computing Morristown, New Jersey
Number of colors (max 8): 2              
Number of positions: 2
Number of rounds: 2
Number of possibilities 4
Color   Letter
=====   ======
BLACK   B
WHITE   W
Round number 1
Guess my combination ...
Move # 1 Guess :
Guess BW
Results: ['BW', 0, 0]
You have 0 blacks and 0 whites
Move # 2 Guess :
Guess WW
Results: ['WW', 0, 0]
You have 0 blacks and 0 whites
Move # 3 Guess :
Guess BB
Results: ['BB', 0, 0]
You have 0 blacks and 0 whites
Move # 4 Guess :
Guess RR
INVALID GUESS: RR
Move # 4 Guess :
Guess BB
Results: ['BB', 0, 0]
You have 0 blacks and 0 whites
Move # 5 Guess :
Guess BWB
BAD NUMBER OF POSITIONS
Move # 5 Guess :
Guess BB
Results: ['BB', 0, 0]
You have 0 blacks and 0 whites
Move # 6 Guess :
Guess WW
Results: ['WW', 0, 0]
You have 0 blacks and 0 whites
Move # 7 Guess :
Guess BW
Results: ['BW', 0, 0]
You have 0 blacks and 0 whites
Move # 8 Guess :
Guess WB
Results: ['WB', 0, 0]
You have 0 blacks and 0 whites
Move # 9 Guess :
Guess ^CTraceback (most recent call last):
```

Here the computer guesses TT.   
```
Mastermind
Creative Computing Morristown, New Jersey
Number of colors (max 8): 2
Number of positions: 2
Number of rounds: 1
Number of possibilities 4
Color   Letter
=====   ======
BLACK   B
WHITE   W
Round number 1
Guess my combination ...
Move # 1 Guess :
Guess BW
Results: ['BW', 0, 2]
You have 0 blacks and 2 whites
Move # 2 Guess :
Guess WB
Results: ['WB', 2, 0]
You guessed it in 2 moves!
SCORE:
     COMPUTER 0
     HUMAN    2
NOW I GUESS. THINK OF A COMBINATION.
HIT RETURN WHEN READY:         
My guess is: TT
ENTER BLACKS, WHITES (e.g. 1,2): 0,0
['TT', 2, 0]
['BB', 0, 0]
['WB', 0, 0]
['BW', 0, 0]
My guess is: BB
ENTER BLACKS, WHITES (e.g. 1,2): 2,0
I GOT IT IN 2 MOVES
SCORE:
     COMPUTER 2
     HUMAN    2
GAME OVER
FINAL SCORE:
     COMPUTER 2
     HUMAN    2

```
Similar to the first example. Three colors, two positions, computer says none of the colors is in the solution. 
```
Mastermind
Creative Computing Morristown, New Jersey
Number of colors (max 8): 3
Number of positions: 2
Number of rounds: 2
Number of possibilities 9
Color   Letter
=====   ======
BLACK   B
WHITE   W
RED     R
Round number 1
Guess my combination ...
Move # 1 Guess :
Guess BB
Results: ['BB', 0, 0]
You have 0 blacks and 0 whites
Move # 2 Guess :
Guess WW
Results: ['WW', 0, 0]
You have 0 blacks and 0 whites
Move # 3 Guess :
Guess RR
Results: ['RR', 0, 0]
You have 0 blacks and 0 whites
Move # 4 Guess :
Guess 

```

**Comment by AnthonyMichaelTDM** [comment]
Is this before or after reverting #611?

**Comment by jnellis** [comment]
After because I was testing each program after reverting. In any regard I don't think this problem is related to that part of the code.  Seems it has a problem when the number of positions is two. I have no idea what the TT (tan color) response was about as that should have been completely out of the realm of possibilities.  I think I read that you ported your rust port from this python port, is that correct? Maybe this the reason you saw funny behavior? 

Also I just notice that the diff on my python change is the whole file. Awesome. No idea about that. Is that a github action thing or my IDE changing carriage returns because windows/linux.

**Comment by jnellis** [comment]
@MartinThoma 

The huge diff on the python file seems like its part of a pre-commit-hook: **mixed line ending** perhaps in pre-commit-config.yaml because on my machine the local diff is just the one line.

https://github.com/pre-commit/pre-commit-hooks#mixed-line-ending

### mixed-line-ending

Replaces or checks mixed line ending.

    --fix={auto,crlf,lf,no}
        auto - Replaces automatically the most frequent line ending. This is the default argument.
        crlf, lf - Forces to replace line ending by respectively CRLF and LF.
            This option isn't compatible with git setup check-in LF check-out CRLF as git smudge this later than the hook is invoked.
        no - Checks if there is any mixed line ending without modifying any file.


I can't decipher what exactly the default is supposed to do but it didn't bork the other files in this same commit.

**Comment by AnthonyMichaelTDM** [comment]
> I think I read that you ported your rust port from this python port, is that correct? Maybe this the reason you saw funny behavior?

I did not, but I figured out the reason I saw errors in my port, I was comparing the possibilities to the answer when filtering them, not to the computers guess. [see here](https://github.com/AnthonyMichaelTDM/basic-computer-games/commit/f745dad4b2d1149df4c358aea450ae928189527b)

I'll probably push those changes soon once I refactor the rust port to follow rust conventions more closely (extract game logic to lib.rs to improve readability of main.rs and make testing logic easier)

**Comment by jnellis** [comment]
Cool, I've figured out the python issues and will push those soon as well.
