### ISSUE TITLE
Typo in the Basic and JavaScript versions of SALVO

### ISSUE THREAD

**Issue by ejolson2005** [coding-horror/basic-computer-games#729]
As per the analysis in

https://forums.raspberrypi.com/viewtopic.php?p=1997950#p1997950

see also the earlier post

https://forums.raspberrypi.com/viewtopic.php?p=1994961#p1994961

in the same thread, there is a typo in later published versions of the SALVO Basic source code compared to the original edition of 101 Basic Computer Games.

This typo is interesting because it causes the program to play by a much weaker strategy while exhibiting no other obvious side effects.  I would recommend changing the line 3970 in the Basic program back to the original
```
3970 K(R,S)=K(R,S)+E(U)-2*INT(H(U)+.5)
```
and to change the JavaScript program accordingly.

**Comment by coding-horror** [comment]
oh, interesting! Let me add this to the readme.md under porting notes.

**Comment by coding-horror** [comment]
Ok, Ive added that note here

https://github.com/coding-horror/basic-computer-games/blob/main/77_Salvo/README.md

The old line is

`3970 K(R,S)=K(R,S)+E(U)-S*INT(H(U)+.5)`

the new line is

`3970 K(R,S)=K(R,S)+E(U)-2*INT(H(U)+.5)`
