### ISSUE TITLE
hangman.rb doesn't randomize the order of puzzle words

### ISSUE THREAD

**Issue by BrBill** [coding-horror/basic-computer-games#730]
The game in BASIC chooses a random order for the words that are selected for each hangman round. In this ruby implementation, the array of available words is just offered to the player in the order they appear in the source.

**Comment by BrBill** [comment]
I can see in the source that it attempts to shuffle the words, but in this version, that shuffling must not work. I tested in Ruby 2.8 and 3.1.

**Comment by BrBill** [comment]
How can I push these changes? Do I need to request collaborator status somehow?

**Comment by jnellis** [comment]
Hi Bill, the common flow is to **fork** this repository to your account. Then you clone your fork to your local development environment (pc, laptop). You make changes and commits on your local environment then **push** those back up to your github fork of this repository. Then from github you can easily submit a pull request to merge changes in your fork to this main repository and then when someone reviews it it will be merged or rejected with comment.

**Comment by BrBill** [comment]
Thanks, @jnellis. I've never had to fork before, so here's to a new thing for me to learn.

**Comment by coding-horror** [comment]
Thanks for noticing this and giving it a fix, BrBill!

**Comment by BrBill** [comment]
All right, got it forked, and made a pull request from my own repo.

**Comment by AnthonyMichaelTDM** [comment]
can this issue be marked as resolved?

**Comment by BrBill** [comment]
Done!

**Comment by BrBill** [comment]
Why is it still open? I closed it. Ugh.
