### ISSUE TITLE
Are less mainstream languages allowed?

### ISSUE THREAD

**Issue by sohang3112** [coding-horror/basic-computer-games#762]
(Asking because I wasn't sure after reading the README) Are solutions in non-mainstream languages (like Clojure, Haskell, etc.) allowed in the Alternate Languages folder?

**PS:** Sorry if I'm abusing Github Issues, but I wasn't sure where to ask questions. Please let me know if there is a better place to ask questions.

**Comment by sohang3112** [comment]
.... And apparently non-mainstream languages *are* allowed in Alternate Languages. Closing issue since I found my answer.

**PS:** Still don't know what is the appropriate place to ask questions - please let me know!

**Comment by mojoaxel** [comment]
Please have a look in the [readme](https://github.com/coding-horror/basic-computer-games#project-structure). There is also a section on [Alternate Languages](https://github.com/coding-horror/basic-computer-games#alternate-languages).

**Comment by mojoaxel** [comment]
> Still don't know what is the appropriate place to ask questions - please let me know!

As long as there are no [github dicussions](https://docs.github.com/en/discussions) or an active stackoverflow tag for a project it is ok to ask questions in an github issue!

**Comment by sohang3112** [comment]
Thanks! @mojoaxel
