### ISSUE TITLE
Confusion between 91_Train and 92_Trap Rust

### ISSUE THREAD

**Issue by ugurkupeli** [coding-horror/basic-computer-games#809]
92_Trap rust folder contains the code for 91_Train

**Comment by AnthonyMichaelTDM** [comment]
oops, I'll fix that real quick.

**Comment by AnthonyMichaelTDM** [comment]
turns out I pushed 91_train's implementation to 91_train and 92_trap, luckily I hadn't overwritten someone else's work when I made that mistake, but still.

**Comment by ugurkupeli** [comment]
I could've sworn I implemented 92 Trap for rust.. I guess not x)
