### ISSUE TITLE
More Basic Computer Games

### ISSUE THREAD

**Issue by melstav** [coding-horror/basic-computer-games#92]
I don't know if you'd seen it before, but I was kind of wondering if you were planning on giving the sequel collection, "More Basic Computer Games" the same treatment.

Scans of the book are on AtariAge and Archive.org, but I was also able to track down a site that had all of the games in plain text, ready to download. https://www.roug.org/retrocomputing/languages/basic/morebasicgames

**Comment by coding-horror** [comment]
Yes, but I wanted to reduce the scope of the project and start with the original book first!

**Comment by melstav** [comment]
I figured that if you were already aware of the book, its omission would likely have been for that very reason, but I thought it was worth confirming.

**Comment by Russtopia** [comment]
Hooray! I eagerly await the definitive set of `Hunt the Wumpus` ports to every language!

Here's a start from [RosettaCode, in GNU APL](https://github.com/Russtopia/wumpus-gnu-apl).

**Comment by coding-horror** [comment]
Let's see how far we get with the first 101 games first, but this is on our roadmap!!

**Comment by journich** [comment]
Closing this one now.  I am also looking forward to contributing to the "More Basic Computer games" effort in due course!
